# Generated by Django 5.1.7 on 2025-03-19 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotofacil_analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='concurso',
            name='ganhadores_15_acertos',
            field=models.IntegerField(default=0),
        ),
    ]
