# Generated by Django 5.1.7 on 2025-03-20 00:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotofacil_analyzer', '0002_concurso_ganhadores_15_acertos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnaliseEstatistica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('frequencia', 'Frequência de Números'), ('atraso', 'Atraso de Números'), ('combinacoes', 'Combinações Mais Comuns'), ('distribuicao', 'Distribuição de Números'), ('outro', 'Outro')], max_length=50)),
                ('data_analise', models.DateTimeField(auto_now_add=True)),
                ('parametros', models.JSONField(blank=True, null=True)),
                ('resultados', models.JSONField()),
            ],
            options={
                'verbose_name': 'Análise Estatística',
                'verbose_name_plural': 'Análises Estatísticas',
                'ordering': ['-data_analise'],
            },
        ),
        migrations.CreateModel(
            name='ApostaGerada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_geracao', models.DateTimeField(auto_now_add=True)),
                ('numeros', models.CharField(max_length=50)),
                ('metodo_geracao', models.CharField(choices=[('frequencia', 'Frequência de Números'), ('combinado', 'Combinação Estatística'), ('aleatorio', 'Aleatório'), ('outro', 'Outro')], max_length=50)),
                ('parametros', models.JSONField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apostas_geradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Aposta Gerada',
                'verbose_name_plural': 'Apostas Geradas',
                'ordering': ['-data_geracao'],
            },
        ),
        migrations.CreateModel(
            name='SorteioLotofacil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concurso', models.IntegerField(unique=True)),
                ('data', models.DateField()),
                ('numeros', models.CharField(max_length=50)),
                ('ganhadores_15_acertos', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Sorteio Lotofácil',
                'verbose_name_plural': 'Sorteios Lotofácil',
                'ordering': ['-concurso'],
            },
        ),
        migrations.DeleteModel(
            name='Concurso',
        ),
        migrations.DeleteModel(
            name='JogoGerado',
        ),
    ]
